name: Build Maven Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      # ✅ Step 3: Build using Maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
